<?php

/**
 * @file
 * Contains hooks for the views_autorefresh module.
 */

use Drupal\views\ViewExecutable;
use Drupal\Core\Link;

/**
 * Implementation of hook_views_ajax_data_alter().
 */
function views_autorefresh_views_ajax_data_alter(&$commands, $view) {
  $autorefresh = views_autorefresh_get_settings($view);
  if (isset($_REQUEST['autorefresh']) && isset($autorefresh)) {
    foreach ($commands as $key => &$command) {
      if (
        !empty($autorefresh['incremental']) &&
        $command['command'] == 'insert' &&
        $command['selector'] == ('.view-dom-id-' . $view->dom_id)
      ) {
        $command['command'] = 'viewsAutoRefreshIncremental';
        $command['view_name'] = $view->name. '-' . $view->current_display;
      }
      if ($command['command'] == 'viewsScrollTop') {
        unset($commands[$key]);
      }
    }
    $timestamp = views_autorefresh_get_timestamp($view);
    if ($timestamp) {
      $commands[] = array(
        'command' => 'viewsAutoRefreshTriggerUpdate',
        'selector' => '.view-dom-id-' . $view->dom_id,
        'timestamp' => $timestamp,
      );
    }
  }
}

/**
 * Implementation of hook_theme().
 */
function views_autorefresh_theme($existing, $type, $theme, $path) {
  return array(
    'views_autorefresh_link' => array(
      'variables' => array(
        'interval' => NULL,
        'timestamp' => NULL,
        'ping' => NULL,
        'incremental' => NULL,
        'view' => NULL,
        'nodejs' => NULL,
      ),
    ),
  );
}

/**
 * Implements default pre-processing for views_autorefresh_link.
 */
function template_preprocess_views_autorefresh_link(&$variables) {
  $view = $variables['view'];
  $variables['content'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['auto-refresh']],
    '#attached' => [
      'library' => ['views_autorefresh/views_autorefresh'],
      'drupalSettings' => [
        'viewsAutorefresh' => [
          $view->id() . '-' . $view->current_display => [
            'interval' => $variables['interval'],
            'timestamp' => $variables['timestamp'],
            //'ping' => $variables['ping'],
            'incremental' => $variables['incremental'],
            //'nodejs' => $variables['nodejs'],
          ]
        ]
      ],
    ],
    'link' => Link::createFromRoute(t('Refresh manually'), '<current>')->toRenderable(),
  ];
}

/**
 * Helper function to get autorefresh settings.
 */
function views_autorefresh_get_settings($view) {
  if (isset($view->display_handler->handlers['header']['autorefresh'])) {
    return $view->display_handler->handlers['header']['autorefresh']->options;
  }
  foreach ($view->display as $id => $display) {
    if (isset($display->display_options['header']['autorefresh'])) {
      return $display->display_options['header']['autorefresh'];
    }
  }
  return NULL;
}

/**
 * Implements hook_views_pre_render().
 *
 * Reset information about first display instead of the second display (incremental approach only)
 * FIXME: Check if it's necessary to reset any further information
 */
function views_autorefresh_views_pre_render(ViewExecutable $view) {
  if (isset($_REQUEST['original_view_data']) &&
      !empty($_REQUEST['original_view_data']['view_display_id']) &&
      isset($_REQUEST['original_view_data']['view_dom_id']) &&
      $_REQUEST['original_view_data']['view_dom_id'] == $view->dom_id
  ) {
    $view->current_display = $_REQUEST['original_view_data']['view_display_id'];
  }
}
/**
 * Refreshes a view through nodejs.
 */
function views_autorefresh_nodejs_refresh($views, $context) {
  foreach ($views as $view_name) {
    $message = (object) array(
      'channel' => 'views_autorefresh_' . $view_name,
      'callback' => 'viewsAutoRefresh',
      'view_name' => $view_name,
    );
    drupal_alter('views_autorefresh_nodejs_message', $message, $context);
    nodejs_send_content_channel_message($message);
  }
}
